---

- name: "configuration play." 
  hosts: WEB
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  tasks: 
    - name : Copy build files to target host
      copy:
        src: /root/project/artifact.tar.gz
        dest: /home/ubuntu/artifact.tar.gz

  roles:
    - deploy
