---
# Task to install npm and nodejs packages
- name: "Install npm and Node.js"
  package:
    name: "{{ item }}"
    state: present
  loop:
    - nodejs
    - npm

# Task to install pm2 globally using npm
- name: "Install pm2 globally"
  npm:
    name: pm2
    global: yes
