- name: Set environment variables
  become: yes
  npm:
    name: udapeople-backend
    global: yes
    state: present

- name: Stop default PM2 process
  become: yes
  command: pm2 stop default

- name: Start PM2 process
  become: yes
  command: pm2 start npm --name "udapeople-backend" -- start
