- name : Copy build files to target host
  copy:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz

- name: Extract artifact.tar.gz
  become: yes
  command: |
    tar -xzvf /home/ubuntu/artifact.tar.gz -C /home/ubuntu
    cd backend

- name: Install npm
  become: yes
  package:
    name: npm
    state: present

- name: Check if default PM2 process is running
  become: yes
  shell: pm2 list | grep -q 'default'
  register: default_pm2_running
  ignore_errors: true

- name: Stop default PM2 process
  become: yes
  command: pm2 stop default
  when: default_pm2_running.rc == 0

- name: Start PM2 process
  become: yes
  command: pm2 start npm  -- start
