- name: Install npm
  become: yes
  package:
    name: npm
    state: present

- name: Stop default PM2 process
  become: yes
  command: pm2 stop default

- name: Start PM2 process
  become: yes
  command: pm2 start npm --name "udapeople-backend" -- start
