---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: install npm && nodejs
  package: 
    name: "{{item}}"
    state: present
  loop:
    - nodejs
    - npm

- name: install pm2 globally
  npm: 
    name: pm2
    global: yes
