---
# Task to update apt packages
- name: "Update apt packages"
  become: yes
  apt:
    update_cache: yes

# Task to upgrade packages
- name: "Upgrade packages"
  become: yes
  apt:
    upgrade: yes
